create table product
(
    product_id  bigint generated by default as identity primary key,
    description varchar(4096),
    in_stock    boolean default false not null,
    name        varchar(255) not null constraint product_name_check check (TRIM(BOTH FROM name) <> ''::text),
    price       numeric(38, 2) default 0 not null
    constraint product_price_check check (price >= (0)::numeric)
);